name: "hello world"
description: "Greet someone and record the time"
inputs:
  version: # id of input
    description: "Version of android sdk"
    required: true
    default: None
outputs:
  version: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.version }}
